spring:
   datasource:
       url: jdbc:mysql://localhost:3306/testdb
       username: root
       password: Nithya@1234
       driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      hibernate:
       ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8686
application:
    name: user-service
logging:
  level:
     org:
       springframework:
            web: DEBUG
       security: DEBUG
     com.logistics.in.config.JwtAuthFilter: DEBUG

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

jwt:
  secret: "R6W/n1mjc8PAnjE8QZZg2gmLQBhVGiM3jPEHFnKz3vY="  

  
